name: 2-hours-cron
on:
  schedule:
    - cron: '0 */2 * * *'
jobs:
  build:
    name: Call our API route
    runs-on: ubuntu-latest
    steps:
        - run: |
              curl --request GET \
              --url 'https://trackify-backend-nu.vercel.app/api/user/cycle' \
